In [1]:
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true =np.array([0.3,0.7,1,0,0.5])

Mean Absolute Error without numpy and numpy

In [4]:
def mae(y_true, y_oredicted):
    total_error =0
    for yt, yp in zip(y_true,y_predicted):
        total_error += abs(yt-yp)
    print("Total error:",total_error)
    mae = total_error / len(y_true)
    print("MAE:",mae)

In [5]:
mae(y_true,y_predicted)

Total error: 2.5
MAE: 0.5


In [6]:
y_predicted -y_true

array([ 0.7,  0.3, -1. ,  0. ,  0.5])

In [7]:
np.abs(y_predicted - y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [9]:
np.sum(np.abs(y_predicted - y_true))

2.5

In [13]:
np.mean(np.abs(y_predicted - y_true)) #MAE using numpy

0.5

Mean Squared Error

In [12]:
np.mean(np.square(y_predicted - y_true))

0.366

In [14]:
def mse(y_true, y_predicted):
    total_error =0
    for yt,yp in zip(y_true,y_predicted):
        total_error += (yt-yp)**2
    print(total_error)
    mse = total_error/len(y_true)
    print(mse)

In [15]:
mse(y_true,y_predicted)

1.83
0.366


Log loss

In [17]:
np.log(0)

C:\Users\meena\AppData\Local\Temp\ipykernel_8968\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [18]:
epsilon = 1e-15

In [19]:
np.log(epsilon)

-34.538776394910684

In [20]:
y_predicted

array([1, 1, 0, 0, 1])

In [24]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [25]:
1-epsilon

0.999999999999999

In [26]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [27]:
y_predicted_new = np.array(y_predicted_new)

In [28]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [29]:
np.log(y_predicted)

C:\Users\meena\AppData\Local\Temp\ipykernel_8968\815880036.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted)


array([  0.,   0., -inf, -inf,   0.])

In [30]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [31]:
def log_loss(y_true, y_predicted):
    y_predicted_new =[max(i,epsilon) for i in y_predicted]
    y_predicted_new =[min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [32]:
log_loss(y_true, y_predicted)

17.2696280766844